# https://gohugo.io/variables/site/

baseURL = "https://www.coinnoicoinna.com"
copyright = "coinnoicoinna"
enableRobotsTXT = true
relativeURLs = true
title = "คอยน์น้อยแต่คอยน์นะ"
languageCode = "th"

[params]
  author = "coinnoicoinna"
  description = "เล่าคริปโตง่าย ๆ ให้ทุกคนเข้าใจ"
  homepageKeywords = ["crypto", "cryptocurrency", "investment", "คริปโต", "คริปโตเคอร์เรนซี"]
  logo = "/apple-icon-114x114.png"

[related]
  includeNewer = true
[[related.indices]]
  name = 'tags'
  weight = 100
[[related.indices]]
  name = 'categories'
  weight = 90
